<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#README" data-toc-modified-id="README-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>README</a></span></li><li><span><a href="#Numpy" data-toc-modified-id="Numpy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Numpy</a></span><ul class="toc-item"><li><span><a href="#Numpy-Methods" data-toc-modified-id="Numpy-Methods-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Numpy Methods</a></span></li><li><span><a href="#Attributes-of-$\texttt{ndarray}$-objects" data-toc-modified-id="Attributes-of-$\texttt{ndarray}$-objects-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Attributes of $\texttt{ndarray}$ objects</a></span></li><li><span><a href="#Numpy-data-types" data-toc-modified-id="Numpy-data-types-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Numpy data types</a></span></li><li><span><a href="#Numpy-special-values" data-toc-modified-id="Numpy-special-values-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Numpy special values</a></span></li><li><span><a href="#Operations-on-$\texttt{ndarrays}$" data-toc-modified-id="Operations-on-$\texttt{ndarrays}$-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Operations on $\texttt{ndarrays}$</a></span><ul class="toc-item"><li><span><a href="#$flatten$-and-$ravel$" data-toc-modified-id="$flatten$-and-$ravel$-2.5.1"><span class="toc-item-num">2.5.1&nbsp;&nbsp;</span>$flatten$ and $ravel$</a></span></li><li><span><a href="#$resize$" data-toc-modified-id="$resize$-2.5.2"><span class="toc-item-num">2.5.2&nbsp;&nbsp;</span>$resize$</a></span></li><li><span><a href="#$reshape$" data-toc-modified-id="$reshape$-2.5.3"><span class="toc-item-num">2.5.3&nbsp;&nbsp;</span>$reshape$</a></span></li><li><span><a href="#$transpose$" data-toc-modified-id="$transpose$-2.5.4"><span class="toc-item-num">2.5.4&nbsp;&nbsp;</span>$transpose$</a></span></li><li><span><a href="#Merging-issues" data-toc-modified-id="Merging-issues-2.5.5"><span class="toc-item-num">2.5.5&nbsp;&nbsp;</span>Merging issues</a></span></li><li><span><a href="#Indexing-and-slicing" data-toc-modified-id="Indexing-and-slicing-2.5.6"><span class="toc-item-num">2.5.6&nbsp;&nbsp;</span>Indexing and slicing</a></span><ul class="toc-item"><li><span><a href="#1-D-numpy-arrays" data-toc-modified-id="1-D-numpy-arrays-2.5.6.1"><span class="toc-item-num">2.5.6.1&nbsp;&nbsp;</span>1-D numpy arrays</a></span></li><li><span><a href="#2-D-numpy-arrays" data-toc-modified-id="2-D-numpy-arrays-2.5.6.2"><span class="toc-item-num">2.5.6.2&nbsp;&nbsp;</span>2-D numpy arrays</a></span></li></ul></li></ul></li><li><span><a href="#Reading-and-writing-arrays" data-toc-modified-id="Reading-and-writing-arrays-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Reading and writing arrays</a></span></li><li><span><a href="#Statistical-methods" data-toc-modified-id="Statistical-methods-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Statistical methods</a></span></li><li><span><a href="#Polynomials" data-toc-modified-id="Polynomials-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>Polynomials</a></span></li><li><span><a href="#Linear-algebra" data-toc-modified-id="Linear-algebra-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>Linear algebra</a></span></li><li><span><a href="#Matrices" data-toc-modified-id="Matrices-2.10"><span class="toc-item-num">2.10&nbsp;&nbsp;</span>Matrices</a></span></li><li><span><a href="#Random-sampling" data-toc-modified-id="Random-sampling-2.11"><span class="toc-item-num">2.11&nbsp;&nbsp;</span>Random sampling</a></span></li></ul></li><li><span><a href="#Scipy" data-toc-modified-id="Scipy-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Scipy</a></span></li></ul></div>

# README

Numpy is a rich, mature and efficient library that supports technical and scientific  computation. At the core of the Numpy library, there's a new object: Numpy's $\texttt{ndarray}$. If Numpy is the engine of computation in Python, Scipy is probably the wheels. Indeed, the Scipy library expands on Numpy by providing users with an impressive variety of functions, which cut across different fields such as engineering, physics, statistics, and operation research.

# Numpy

In [1]:
A = [1, 4, 5]
B = [2, 4, 6]

C = []

for i in range(n):
    C.append(A[i] * B[i])
    
C = A * B

NameError: name 'n' is not defined

## Numpy Methods

In [2]:
import numpy as np

In [3]:
# initializing a Numpy array
A = np.array([1, 4, 3])

In [4]:
# initializing a Numpy array using np.arange
B = np.arange

In [5]:
B

<function numpy.arange>

In [6]:
# initializing a Numpy array using np.linspace
C = np.linspace(1, 10, 5)

In [7]:
C

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [8]:
# initializing a Numpy array using custom function
def f(i, j):
    return 2 * i * j

D = np.fromfunction(f, (2, 3))

D

array([[0., 0., 0.],
       [0., 2., 4.]])

## Attributes of $\texttt{ndarray}$ objects 

$\texttt{ndarray}$ attributes

Attribute | Description
----------|--------
shape | The array dimensions: the size of the array along each of its axes, returned as a tuple of integers
ndim | Number of axes (dimensions). Note that ndim == len(shape)
size | The total number of elements in the array, equal to the product of the elements of shape
dtype | The array’s data type (see Section 6.1.2)
data | The “buffer” in memory containing the actual elements of the array
itemsize | The size in bytes of each element

In [9]:
D.shape

(2, 3)

In [10]:
D.ndim

2

In [11]:
C.ndim

1

In [12]:
D.size

6

In [13]:
D.dtype

dtype('float64')

## Numpy data types

Data Type | Description
----------|------------
int_      | The default integer type
int8      | Integer in a single byte: -128 to 127
int16     | Integer in 2 bytes: -32768 to 32767
int32     | Integer in 4 bytes: -2147483648 to 2147483647
int64     | Integer in 8 bytes: $−2^{63}$ to $2^{63}$ − 1
uint8     | Unsigned integer in a single byte: 0 to 255 
uint16    | Unsigned integer in 2 bytes: 0 to 65535
uint32    | Unsigned integer in 4 bytes: 0 to 4294967295
uint64    | Unsigned integer in 8 bytes: 0 to $2^{64}$ − 1
float_    | The default floatng point number type, another name for float64
float32   | Single-precision, signed float: ∼ 10 −38 to ∼ 10 38 with ∼ 7 decimal digits of precision 
float64   |Double-precision, signed float: ∼ 10 −308 to ∼ 10 308 with ∼ 15 decimal digits of precision
complex_  | The default complex number type, another name for complex128
complex64 | Single-precision complex number (represented by 32-bit floating point real and imaginary components)
complex128| Double-precision complex number (represented by 64-bit floating point real and imaginary components)
bool_     | The default boolean type represented by a single byte

## Numpy special values

In [14]:
np.nan

nan

In [15]:
np.inf

inf

In [16]:
A = np.arange(3)

In [17]:
A/0

<ipython-input-17-986c576c79e7>:1: RuntimeWarning: divide by zero encountered in true_divide
  A/0
<ipython-input-17-986c576c79e7>:1: RuntimeWarning: invalid value encountered in true_divide
  A/0


array([nan, inf, inf])

## Operations on $\texttt{ndarrays}$

### $flatten$ and $ravel$

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
A.shape

(3, 3)

In [20]:
A.ndim

2

In [21]:
# flatten
B = A.flatten()
B

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
B.shape

(9,)

In [23]:
B.ndim

1

In [24]:
# ravel 
C = A.ravel()

In [25]:
C

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### $resize$

In [26]:
A = np.linspace(1, 4, 4)
A

array([1., 2., 3., 4.])

In [27]:
A.resize(2, 2)

In [28]:
A

array([[1., 2.],
       [3., 4.]])

### $reshape$

In [29]:
A = np.linspace(1, 4, 4)
A

array([1., 2., 3., 4.])

In [30]:
B = A.reshape(2, 2)

In [31]:
B

array([[1., 2.],
       [3., 4.]])

### $transpose$

In [32]:
A = np.linspace(1, 6, 6).reshape(3,2)
A

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [33]:
A.transpose()

array([[1., 3., 5.],
       [2., 4., 6.]])

### Merging issues

In [34]:
A = np.array([0, 0, 0, 0])
B = np.array([1, 1, 1, 1])
C = np.array([2, 2, 2, 2])
A, B, C

(array([0, 0, 0, 0]), array([1, 1, 1, 1]), array([2, 2, 2, 2]))

In [35]:
# 'vstack' 
np.vstack((A, B, C))

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [36]:
# 'hstack'
np.hstack((A, B, C))

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [37]:
# 'dstack'
>>> a = np.array((1,2,3))
>>> b = np.array((2,3,4))
>>> np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [38]:
# 'hsplit'
A = np.arange(6)
A

array([0, 1, 2, 3, 4, 5])

In [39]:
np.hsplit(A, 3)

[array([0, 1]), array([2, 3]), array([4, 5])]

### Indexing and slicing

#### 1-D numpy arrays

In [40]:
A = np.linspace(1, 6, 6)
A 

array([1., 2., 3., 4., 5., 6.])

In [41]:
A[0]

1.0

In [42]:
A[1:4]

array([2., 3., 4.])

In [43]:
A[1:4:2]

array([2., 4.])

In [44]:
A[3::-2]

array([4., 2.])

#### 2-D numpy arrays

In [45]:
B = np.linspace(1, 12, 12).reshape(4, 3)
B

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [46]:
B[3, 1]

11.0

In [47]:
B[:, 2]

array([ 3.,  6.,  9., 12.])

## Reading and writing arrays

In [48]:
A = np.linspace(1, 6, 6)
A

array([1., 2., 3., 4., 5., 6.])

In [49]:
np.save("simple_numpy.npy", A)

In [50]:
B = np.load("simple_numpy.npy")
B

array([1., 2., 3., 4., 5., 6.])

In [51]:
np.loadtxt?

Signature:
np.loadtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    converters=None,
    skiprows=0,
    usecols=None,
    unpack=False,
    ndmin=0,
    encoding='bytes',
    max_rows=None,
    *,
    like=None,
)
Docstring:
Load data from a text file.

Each row in the text file must have the same number of values.

Parameters
----------
fname : file, str, or pathlib.Path
    File, filename, or generator to read.  If the filename extension is
    ``.gz`` or ``.bz2``, the file is first decompressed. Note that
    generators should return byte strings.
dtype : data-type, optional
    Data-type of the resulting array; default: float.  If this is a
    structured data-type, the resulting array will be 1-dimensional, and
    each row will be interpreted as an element of the array.  In this
    case, the number of columns used must match the number of fields in
    the data-type.
comments : str or sequence of str, optional
    The characters or list of cha

In [52]:
FILE = "eg6-a-student-data.txt"
DTYPE = np.dtype([("gender", "|S1"), ("height", "f8")])
A = np.loadtxt(FILE, dtype=DTYPE, skiprows=9, usecols=(1, 3))
A

array([(b'M', 1.82), (b'M', 1.77), (b'F', 1.68), (b'M', 1.72),
       (b'F', 1.78), (b'F', 1.6 ), (b'M', 1.72), (b'M', 1.83),
       (b'F', 1.56), (b'F', 1.64), (b'M', 1.63), (b'M', 1.67),
       (b'M', 1.66), (b'F', 1.59), (b'F', 1.7 ), (b'M', 1.97),
       (b'F', 1.66), (b'F', 1.63), (b'M', 1.69)],
      dtype=[('gender', 'S1'), ('height', '<f8')])

## Statistical methods

In [53]:
A = np.array([0, 15, 3, 5, 8, 9])
A

array([ 0, 15,  3,  5,  8,  9])

In [54]:
np.mean(A)

6.666666666666667

In [55]:
np.min(A), np.max(A)

(0, 15)

In [56]:
np.std(A)

4.784233364802441

## Polynomials

In [57]:
np.polynomial.Polynomial?

Init signature: np.polynomial.Polynomial(coef, domain=None, window=None)
Docstring:     
A power series class.

The Polynomial class provides the standard Python numerical methods
'+', '-', '*', '//', '%', 'divmod', '**', and '()' as well as the
attributes and methods listed in the `ABCPolyBase` documentation.

Parameters
----------
coef : array_like
    Polynomial coefficients in order of increasing degree, i.e.,
    ``(1, 2, 3)`` give ``1 + 2*x + 3*x**2``.
domain : (2,) array_like, optional
    Domain to use. The interval ``[domain[0], domain[1]]`` is mapped
    to the interval ``[window[0], window[1]]`` by shifting and scaling.
    The default value is [-1, 1].
window : (2,) array_like, optional
    Window, see `domain` for its use. The default value is [-1, 1].

    .. versionadded:: 1.6.0
File:           c:\users\mattheus\anaconda3\lib\site-packages\numpy\polynomial\polynomial.py
Type:           ABCMeta
Subclasses:     


$P(x) = 4 + 5x + 2x^2$

In [58]:
P = np.polynomial.Polynomial([4, 5, 2])

In [59]:
P

Polynomial([4., 5., 2.], domain=[-1,  1], window=[-1,  1])

In [60]:
P(4)

56.0

In [61]:
X = np.linspace(-4, 4, 9)
X

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [62]:
P(X)

array([16.,  7.,  2.,  1.,  4., 11., 22., 37., 56.])

## Linear algebra

In [63]:
# multiplication by a scalar
A = np.array([[0, 0.5], [-1, 2]])
A * 4

array([[ 0.,  2.],
       [-4.,  8.]])

In [64]:
# dot product
B = np.array([[2, -0.5], [3, 1.5]])
A.dot(B)

array([[1.5 , 0.75],
       [4.  , 3.5 ]])

In [65]:
np.dot(A, B)

array([[1.5 , 0.75],
       [4.  , 3.5 ]])

In [66]:
# linear algebra module
np.linalg?

Type:        module
String form: <module 'numpy.linalg' from 'C:\\Users\\Mattheus\\anaconda3\\lib\\site-packages\\numpy\\linalg\\__init__.py'>
File:        c:\users\mattheus\anaconda3\lib\site-packages\numpy\linalg\__init__.py
Docstring:  
``numpy.linalg``

The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
low level implementations of standard linear algebra algorithms. Those
libraries may be provided by NumPy itself using C versions of a subset of their
reference implementations but, when possible, highly optimized libraries that
take advantage of specialized processor functionality are preferred. Examples
of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries
are multithreaded and processor dependent, environmental variables and external
packages such as threadpoolctl may be needed to control the number of threads
or specify the processor architecture.

- OpenBLAS: https://www.openblas.net/
- threadpoolctl: https://github.com/joblib

## Matrices

In [67]:
A = np.matrix([[0, -1], [1, -2]])
B = np.matrix("0 -1; 1 -2")
A, B

(matrix([[ 0, -1],
         [ 1, -2]]),
 matrix([[ 0, -1],
         [ 1, -2]]))

In [68]:
A * B

matrix([[-1,  2],
        [-2,  3]])

## Random sampling

In [69]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\Mattheus\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\mattheus\anaconda3\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initialize 

In [70]:
np.random.seed?

Docstring:
seed(self, seed=None)

Reseed a legacy MT19937 BitGenerator

Notes
-----
This is a convenience, legacy function.

The best practice is to **not** reseed a BitGenerator, rather to
recreate a new one. This method is here for legacy reasons.
This example demonstrates best practice.

>>> from numpy.random import MT19937
>>> from numpy.random import RandomState, SeedSequence
>>> rs = RandomState(MT19937(SeedSequence(123456789)))
# Later, you want to restart the stream
>>> rs = RandomState(MT19937(SeedSequence(987654321)))
Type:      builtin_function_or_method


In [77]:
np.random.seed(000)

In [78]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

In [79]:
np.random.randint(0, 11, 10)

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [73]:
np.random.seed(000)
np.random.randint(1, 10, 10)

array([6, 1, 4, 4, 8, 4, 6, 3, 5, 8])

In [74]:
# 'randn'
A = np.random.randn(100)
np.mean(A), np.std(A)

(0.1219894380409146, 0.9011537653713609)

In [75]:
len(A)

100

In [76]:
A.shape

(100,)

# Scipy

Scipy is one of the most exciting libraries for Pythonists working on technical and scientific computing. Find out more @ [scipy.org](https://docs.scipy.org/doc/scipy/reference/)!